---
title: "Tidy Dataset"
author: "Trevor VanVeldhuisen, Jonathan VanOyen, Grace Schotanus"
date: '`r format(Sys.Date(), "%B %d, %Y")`'
output: 
  pdf_document:
    fig_height: 2.2
    fig_width: 4
  html_document:
    fig_height: 2.2
    fig_width: 4
  word_document:
    fig_height: 2.2
    fig_width: 4
---

```{r, setup, include = FALSE}
# load packages that are going to be used
require(tidyverse)   # this loads mosaic, ggformula, etc. too
require(ggformula)
require(mosaic)

# Some customization.  You can alter or delete as desired (if you know what you are doing).

theme_set(theme_bw(base_size=12))     # change theme for ggplot2/ggformula

knitr::opts_chunk$set(
  echo = TRUE,      # for homework, always show R code (this is the default)
  tidy = FALSE,     # display code as typed (rather than reformatted)
  size = "small",   # slightly smaller font for code
  message = FALSE, warning = FALSE) # don't print warnings or messages in compiled document. So you MUST check them in RStudio!
```


```{r}
dolphin1 <- read_csv('110608-Behavior_QC.csv') 
```
```{r}
glimpse(dolphin1)
```

```{r}
wide_dolph_dives <- dolphin1 %>%
  pivot_wider(names_from = What,
              values_from = c(duration, DurationMin, DurationMax, Shallow, start , end, Start,End))
glimpse(wide_dolph_dives)
```

```


  