---
title: "Stat 245 Graphics: Nefarious Consultant Requests"
author: "Trevor VanVeldhuisen"
date: '`r format(Sys.Date(), "%B %d, %Y")`'
output: 
  pdf_document:
    fig_height: 4
    fig_width: 6
  html_document:
    fig_height: 4
    fig_width: 6
  word_document:
    fig_height: 4
    fig_width: 6
---

```{r, setup, include = FALSE}
# load packages that are going to be used
require(tidyverse)   # this loads mosaic, ggformula, etc. too
require(ggformula)
require(mosaic)

# Some customization.  You can alter or delete as desired (if you know what you are doing).

theme_set(theme_bw(base_size=12))     # change theme for ggplot2/ggformula

knitr::opts_chunk$set(
  echo = TRUE,      # for homework, always show R code (this is the default)
  tidy = FALSE,     # display code as typed (rather than reformatted)
  size = "small",   # slightly smaller font for code
  message = FALSE, warning = FALSE) # don't print warnings or messages in compiled document. So you MUST check them in RStudio!
```


<!-- Put your work below here.  Put text in text chunks, code in R chunks. -->
```{r}
nefarious <- read_csv('https://sldr.netlify.app/data/nefarious.csv')
```

```{r}
gf_histogram( ~ total_nefarious, data = nefarious) %>%
  gf_labs(title = 'Distribution of Total Nefarious',
          x = 'Total Nefarious',
          y = 'Count of Consultant Statisticians')
```

```{r}
gf_point(age_group ~ total_nefarious,
         data = nefarious,
         color = ~sex,
         size = ~total_nefarious) %>%
  gf_labs( title = 'Age Group and Sex to Total Nefarious',
           x = 'Total Nefarious',
           y = 'Age Group')
```

```{r}
gf_bar( ~ total_nefarious, fill = ~race, data = nefarious) %>%
  gf_labs( title = 'Count of Total Nefarious Based on Race',
           x = 'Total Nefarious',
           y = 'Count of Consultant Statisticians') %>%
  gf_theme(scale_fill_discrete('Race'))
```




### Problem 0.0

### Problem ?.?




  